spring:
  application:
    name: SSN_Web_API
  boot:
    admin:
      notify:
        pagerduty:
          client-url: http://localhost:9003
          instance:
            perfer-ip: true
            
server:
  port: 7001
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzone: http://localhost:8761/eureka/
      
      
  instance:
    hostname: localhost
    
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
      
      
    
